# Generated by Django 5.2.7 on 2025-10-19 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("publications", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="independent_articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Articles published independently by this journalist",
                related_name="independent_authors",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="independent_newsletters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Newsletters published independently by this journalist",
                related_name="independent_authors",
                to="publications.newsletter",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Journalists this reader follows",
                related_name="reader_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Publishers this reader follows",
                related_name="subscribed_readers",
                to="publications.publication",
            ),
        ),
    ]
