# Generated by Django 5.2.7 on 2025-10-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_independent_articles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="independent_newsletters",
        ),
    ]
