# Generated by Django 5.2.7 on 2025-10-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("publications", "0002_delete_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(
                blank=True, help_text="Used for newsletters or short-form content."
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[("article", "Article"), ("newsletter", "Newsletter")],
                default="article",
                help_text="Choose 'Article' for multi-block content, or 'Newsletter' for simple text content.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="publications.publication",
            ),
        ),
    ]
