# Generated by Django 5.2.7 on 2025-10-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArticleBlock",
        ),
    ]
