# Generated by Django 5.2.7 on 2025-10-22 18:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_delete_articleblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Content"
            ),
        ),
    ]
