# Generated by Django 5.2.7 on 2025-10-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
