# Generated by Django 5.2.7 on 2025-10-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
        ("users", "0003_remove_user_independent_newsletters"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newsletter",
        ),
    ]
