# Generated by Django 5.2.7 on 2025-10-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_delete_newsletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="editors",
            new_name="editor",
        ),
    ]
