# Generated by Django 5.2.7 on 2025-10-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_rename_editors_publication_editor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="editor",
            new_name="editors",
        ),
    ]
