# Generated by Django 5.2.7 on 2025-10-21 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_delete_newsletter"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscriber_publication",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscriber_journalist",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("subscriber", "publication", "journalist")},
        ),
    ]
